### ISSUE TITLE
0.8 fails to build with rusttls

### ISSUE THREAD

**Issue by wez** [jayjamesjay/http_req#48]
This is the error I see when upgrading from 0.7 -> 0.8:

```
   Compiling webpki v0.22.0
   Compiling webpki-roots v0.22.0
   Compiling http_req v0.8.0
error[E0308]: mismatched types
  --> /home/wez/.cargo/registry/src/github.com-1ecc6299db9ec823/http_req-0.8.0/src/tls.rs:82:39
   |
82 |             .add_server_trust_anchors(&webpki_roots::TLS_SERVER_ROOTS);
   |                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected struct `webpki::TLSServerTrustAnchors`, found struct `TlsServerTrustAnchors`
   |
   = note: expected reference `&webpki::TLSServerTrustAnchors<'_>`
              found reference `&TlsServerTrustAnchors<'static>`

error[E0308]: try expression alternatives have incompatible types
   --> /home/wez/.cargo/registry/src/github.com-1ecc6299db9ec823/http_req-0.8.0/src/tls.rs:148:13
    |
148 | /             webpki::DNSNameRef::try_from_ascii_str(hostname.as_ref())
149 | |                 .map_err(|_| HttpError::Tls)?,
    | |_____________________________________________^ expected struct `webpki::name::DNSNameRef`, found struct `DnsNameRef`
```

**Comment by wez** [comment]
https://github.com/wez/wezterm/pull/924/checks?check_run_id=2985971507 is dependabot trying to upgrade this on my behalf

**Comment by jayjamesjay** [comment]
Thanks for posting the issue. `rustls` doesn't currently support new versions of `webpki` and `webpki-roots`. I've reverted `webpki` and `webpki-roots` to version `0.21`. Please let know if everything works correctly now.

**Comment by wez** [comment]
Thanks; I actually switched to not using rusttls in the meantime so I'm unblocked either way!

I'd suggest adding something like this to your GH action for future proofing!

```yaml
    - name: Build with Rusttls
      run: cargo build --verbose --features rusttls
```

**Comment by jayjamesjay** [comment]
Ok, thanks
